"""Writes the Xbox build's function table from project/generated/register_functions.cpp.

The generated table has a slot for every 4-byte guest address in the code
region (about 245,000 slots, 1 MB) filled in by a constructor. The Xbox has
64 MB, so it gets two sorted arrays of the used entries instead, statically
initialised; ps2_runtime.cpp looks addresses up by binary search there.
direct_calls.py reads the address array back out of the output (a target's
slot is its index there) to resolve the generated files' constant calls.

usage: compact_function_table.py <register_functions.cpp> <output.cpp>
"""
import re
import sys

source, output = sys.argv[1], sys.argv[2]
text = open(source).read()
base = int(re.search(r"g_ps2RecompiledFunctionTableBase = (0x[0-9a-fA-F]+)u", text).group(1), 16)
end = int(re.search(r"g_ps2RecompiledFunctionTableEnd = (0x[0-9a-fA-F]+)u", text).group(1), 16)
entries = {}
for slot, name in re.findall(r"g_ps2RecompiledFunctionTable\[(\d+)\] = (\w+);", text):
    entries[base + int(slot) * 4] = name
includes = [line for line in text.splitlines() if line.startswith("#include")]
addresses = sorted(entries)

lines = ["// Generated by src/xbox/tools/compact_function_table.py; do not edit."]
lines += includes
lines.append("")
lines.append("extern const uint32_t g_ps2RecompiledFunctionTableBase = 0x%xu;" % base)
lines.append("extern const uint32_t g_ps2RecompiledFunctionTableEnd = 0x%xu;" % end)
lines.append("extern const uint32_t g_ps2RecompiledFunctionTableSlotCount = %du;" % len(addresses))
lines.append("extern const uint32_t g_ps2RecompiledFunctionAddresses[%d] = {" % len(addresses))
lines += ["    0x%xu," % a for a in addresses]
lines.append("};")
lines.append("PS2Runtime::RecompiledFunction g_ps2RecompiledFunctionTable[%d] = {" % len(addresses))
lines += ["    %s," % entries[a] for a in addresses]
lines.append("};")
open(output, "w").write("\n".join(lines) + "\n")
