// Regression coverage for reconstructed TimeSplitters GIF stream/frame fixes.
#include "MiniTest.h"
#include "runtime/gs/gs_frontend.h"
#include "runtime/ps2_memory.h"
#include <algorithm>
#include <cstring>
#include <memory>

namespace {
using Bytes=std::vector<uint8_t>;
void u64(Bytes& b,uint64_t v){const auto n=b.size();b.resize(n+8);std::memcpy(b.data()+n,&v,8);}
void tag(Bytes& b,unsigned loops,unsigned fmt,unsigned nreg,uint64_t regs){u64(b,uint64_t(loops)|0x8000ull|(uint64_t(fmt)<<58)|(uint64_t(nreg)<<60));u64(b,regs);}
void ad(Bytes& b,uint64_t value,uint64_t reg){u64(b,value);u64(b,reg);}
Bytes image(unsigned fmt=2){Bytes b;tag(b,3,fmt,0,0);for(unsigned i=0;i<48;++i)b.push_back(uint8_t(17+3*i));return b;}
Bytes setup(){Bytes b;tag(b,4,0,1,14);ad(b,(64ull<<32)|(1ull<<48)|(1ull<<56),GS_REG_BITBLTBUF);ad(b,0,GS_REG_TRXPOS);ad(b,16ull|(1ull<<32),GS_REG_TRXREG);ad(b,0,GS_REG_TRXDIR);return b;}
struct Fixture {Bytes vram=Bytes(PS2_GS_VRAM_SIZE);GSRegisters regs{};GS gs;Fixture(){gs.init(vram.data(),uint32_t(vram.size()),&regs);}void feed(const Bytes&b,GifPathId p=GifPathId::Path3){gs.processGIFPacket(b.data(),uint32_t(b.size()),p);} bool pixels(){for(unsigned x=0;x<16;++x){uint32_t expected=uint8_t(17+9*x)|(uint32_t(uint8_t(20+9*x))<<8)|(uint32_t(uint8_t(23+9*x))<<16);if((gs.ReadVram(GS_PSM_CT24,64,1,x,0)&0xffffffu)!=expected)return false;}return gs.getDebugSnapshot().transferCopiedPixels==16;}};
// Test-only backend captures submitted Q and the CSR value observed during Present.
struct Recorder final:GSRasterBackend {
 GSRegisters* regs=nullptr; std::vector<GSPrimitiveBatch> batches;uint64_t csrDuringPresent=0;unsigned presents=0;
 void Initialize(uint8_t*,uint32_t)override{} void Reset()override{batches.clear();}
 void Submit(const GSPrimitiveBatch&b)override{batches.push_back(b);}void LoadClut(const GSTex0Reg&,const GSTexClutReg&)override{}
 void BeginTransfer(const GSTransferCommand&)override{}void UploadImage(const uint8_t*,uint32_t)override{}
 void Flush()override{}void TextureFlush()override{}void Sync(GSSyncReason)override{}
 PresentationFrame Present(const GSPresentationRequest&)override{++presents;csrDuringPresent=regs?regs->csr.load():0;PresentationFrame p;p.width=p.height=1;p.pixels={uint8_t(presents),2,3,255};return p;}
 bool ClearFramebuffer(const GSContext&,uint32_t)override{return false;}uint32_t ConsumeLocalToHostBytes(uint8_t*,uint32_t)override{return 0;}
 uint32_t ReadVram(uint32_t,uint32_t,uint32_t,uint32_t,uint32_t)const override{return 0;}
 void WriteVram(uint32_t,uint32_t,uint32_t,uint32_t,uint32_t,uint32_t)override{}
 void SnapshotVram(std::vector<uint8_t>&o)const override{o.clear();}GSTransferSnapshot GetTransferSnapshot()const override{return {};}
};
}
void register_ps2_gif_stream_tests(){MiniTest::Case("TSGifStream",[](TestCase&tc){
 tc.Run("IMAGE transfer survives every byte split including tag and CT24 texel",[](TestCase&t){for(unsigned split=1;split<64;++split){Fixture f;f.feed(setup());auto b=image();f.gs.processGIFPacket(b.data(),split);f.gs.processGIFPacket(b.data()+split,unsigned(b.size())-split);t.IsTrue(f.pixels(),"CT24 transfer failed at split "+std::to_string(split));}});
 tc.Run("PACKED setup and IMAGE can arrive one byte at a time",[](TestCase&t){Fixture f;auto b=setup();auto im=image();b.insert(b.end(),im.begin(),im.end());for(const auto&byte:b)f.gs.processGIFPacket(&byte,1);t.IsTrue(f.pixels(),"byte stream must reconstruct original pixels");});
 tc.Run("IMAGE2 uses the same persistent transfer semantics",[](TestCase&t){Fixture f;f.feed(setup());auto b=image(3);f.gs.processGIFPacket(b.data(),16);f.gs.processGIFPacket(b.data()+16,48);t.IsTrue(f.pixels(),"IMAGE2 exact pixels");});
 tc.Run("independent PATH2 packet cannot consume pending PATH3 image",[](TestCase&t){Fixture f;f.feed(setup());auto b=image();f.gs.processGIFPacket(b.data(),23,GifPathId::Path3);Bytes p2;tag(p2,1,0,1,14);ad(p2,1,GS_REG_COLCLAMP);f.feed(p2,GifPathId::Path2);f.gs.processGIFPacket(b.data()+23,41,GifPathId::Path3);t.IsTrue(f.pixels(),"PATH3 resumes without treating PATH2 as image data");t.Equals(f.gs.getDebugSnapshot().colclamp,1ull,"PATH2 write executes");});
 tc.Run("three physical paths retain different partial PACKED tags",[](TestCase&t){Fixture f;Bytes a,b,c;tag(a,1,0,1,14);ad(a,1,GS_REG_COLCLAMP);tag(b,1,0,1,14);ad(b,1,GS_REG_DTHE);tag(c,1,0,1,14);ad(c,2,GS_REG_SCANMSK);auto send=[&](Bytes&x,GifPathId path,unsigned split){f.gs.processGIFPacket(x.data(),split,path);};send(a,GifPathId::Path1,7);send(b,GifPathId::Path2,19);send(c,GifPathId::Path3,27);f.gs.processGIFPacket(c.data()+27,5,GifPathId::Path3);f.gs.processGIFPacket(a.data()+7,25,GifPathId::Path1);f.gs.processGIFPacket(b.data()+19,13,GifPathId::Path2);auto q=f.gs.getDebugSnapshot();t.Equals(q.colclamp,1ull,"PATH1");t.Equals(q.dthe,1ull,"PATH2");t.Equals(q.scanmsk,2ull,"PATH3");});
 tc.Run("odd REGLIST consumes padding before next tag",[](TestCase&t){Fixture f;Bytes b;tag(b,1,1,1,0);u64(b,6);u64(b,~0ull);tag(b,1,0,1,14);ad(b,1,GS_REG_DTHE);for(size_t i=0;i<b.size();i+=3)f.gs.processGIFPacket(b.data()+i,unsigned(std::min(size_t(3),b.size()-i)));t.Equals(f.gs.getDebugSnapshot().prim.type,6u,"REGLIST PRIM");t.Equals(f.gs.getDebugSnapshot().dthe,1ull,"packet after odd padding");});
 tc.Run("NREG zero is sixteen registers not empty",[](TestCase&t){Fixture f;Bytes b;tag(b,1,1,0,0x0000000000000000ull);for(unsigned i=0;i<16;++i)u64(b,i&7u);f.gs.processGIFPacket(b.data(),24);f.gs.processGIFPacket(b.data()+24,unsigned(b.size()-24));t.Equals(f.gs.getDebugSnapshot().prim.type,7u,"all sixteen PRIM writes consumed");});
 tc.Run("reset discards a pending IMAGE rather than consuming next frame",[](TestCase&t){Fixture f;f.feed(setup());auto b=image();f.gs.processGIFPacket(b.data(),27);f.gs.reset();f.feed(setup());f.feed(image());t.IsTrue(f.pixels(),"reset removes stale transfer fragments");});
 tc.Run("complete PACKED A D write is immediate before EOP completion",[](TestCase&t){Fixture f;Bytes b;tag(b,2,0,1,14);ad(b,1,GS_REG_DTHE);ad(b,1,GS_REG_COLCLAMP);f.gs.processGIFPacket(b.data(),32);t.Equals(f.gs.getDebugSnapshot().dthe,1ull,"first register visible before second");f.gs.processGIFPacket(b.data()+32,16);t.Equals(f.gs.getDebugSnapshot().colclamp,1ull,"second register resumes");});
 tc.Run("PACKED Q survives fragments and intervening physical path",[](TestCase&t){Fixture f;auto ptr=std::make_unique<Recorder>();auto*rec=ptr.get();f.gs.setRasterBackend(std::move(ptr));Bytes p;tag(p,1,0,3,0x512);u64(p,0);u64(p,0x40000000u);ad(p,0x0000002200000011ull,0x0000004400000033ull);ad(p,0,0);f.gs.processGIFPacket(p.data(),32,GifPathId::Path3);Bytes other;tag(other,1,0,1,14);ad(other,1,GS_REG_DTHE);f.feed(other,GifPathId::Path1);f.gs.processGIFPacket(p.data()+32,32,GifPathId::Path3);t.Equals(rec->batches.size(),size_t(1),"point submitted");if(!rec->batches.empty())t.Equals(rec->batches[0].vertices[0].q,2.0f,"ST Q is retained");});
 tc.Run("SIGNAL publishes before guest completion and does not publish FINISH",[](TestCase&t){Fixture f;auto p=std::make_unique<Recorder>();auto*rec=p.get();rec->regs=&f.regs;f.gs.setRasterBackend(std::move(p));f.regs.csr.store(0);f.gs.setHostPresentationMode(GS::HostPresentationMode::Signal);auto n=f.gs.hostPresentationSequence();f.gs.writeRegister(GS_REG_FINISH,0);t.Equals(f.gs.hostPresentationSequence(),n,"FINISH not selected");f.gs.writeRegister(GS_REG_SIGNAL,0xffffffff00000001ull);t.Equals(rec->presents,1u,"SIGNAL presents once");t.Equals(rec->csrDuringPresent&1ull,0ull,"guest SIGNAL not exposed before publication");t.Equals(f.regs.csr.load()&1ull,1ull,"original completion exposed afterward");t.Equals(f.gs.hostPresentationSequence(),n+1,"new frame sequence");});
 tc.Run("FINISH mode and reset advance publication without stale frame",[](TestCase&t){Fixture f;auto p=std::make_unique<Recorder>();auto*rec=p.get();rec->regs=&f.regs;f.gs.setRasterBackend(std::move(p));f.regs.csr.store(0);f.gs.setHostPresentationMode(GS::HostPresentationMode::Finish);auto n=f.gs.hostPresentationSequence();f.gs.writeRegister(GS_REG_SIGNAL,0);t.Equals(f.gs.hostPresentationSequence(),n,"SIGNAL not selected");f.gs.writeRegister(GS_REG_FINISH,0);t.Equals(rec->presents,1u,"FINISH publishes");t.Equals(rec->csrDuringPresent&2ull,0ull,"guest FINISH follows frame");Bytes frame;uint32_t w=0,h=0;t.IsTrue(f.gs.copyLatchedHostPresentationFrame(frame,w,h),"frame copied");f.gs.reset();t.IsFalse(f.gs.copyLatchedHostPresentationFrame(frame,w,h),"reset invalidates frame");t.IsTrue(f.gs.hostPresentationSequence()>n+1,"reset invalidates host upload sequence");});
 tc.Run("arbiter callback carries physical path even for byte fragments",[](TestCase&t){GifArbiter a;std::vector<GifPathId> paths;Bytes got;const uint8_t b=0x73;a.setProcessPathPacketFn([&](GifPathId p,const uint8_t*d,uint32_t n){paths.push_back(p);got.insert(got.end(),d,d+n);});a.submit(GifPathId::Path3,&b,1);a.drain();a.submit(GifPathId::Path1,&b,1);a.drain();t.Equals(paths.size(),size_t(2),"both fragments delivered");t.IsTrue(paths.size()==2&&paths[0]==GifPathId::Path3&&paths[1]==GifPathId::Path1,"path identities preserved");t.Equals(got.size(),size_t(2),"byte lengths preserved");});
 });}
