#!/usr/bin/env python3
"""Convert preserved key-event probe schedules into TS_PAD_SCRIPT timed frames."""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

DIGITAL_KEYS = {
    "Return": "start",
    "x": "cross",
    "space": "cross",
    "c": "circle",
    "z": "square",
    "v": "triangle",
    "q": "l1",
    "e": "r1",
    "Shift_L": "l2",
    "Shift_R": "r2",
    "Tab": "select",
    "Up": "up",
    "Down": "down",
    "Left": "left",
    "Right": "right",
}

VALID_KEYS = set(DIGITAL_KEYS) | {"w", "a", "s", "d", "i", "j", "k", "l"}


def axis(negative: bool, positive: bool) -> int:
    if negative == positive:
        return 128
    return 1 if negative else 255


def fmt_time(value: float) -> str:
    text = f"{value:.3f}".rstrip("0").rstrip(".")
    return text or "0"


def active_frame(active: set[str]) -> tuple[str, int, int, int, int]:
    buttons = [DIGITAL_KEYS[key] for key in sorted(active) if key in DIGITAL_KEYS]
    lx = axis("a" in active, "d" in active)
    ly = axis("w" in active, "s" in active)
    rx = axis("j" in active, "l" in active)
    ry = axis("i" in active, "k" in active)
    return ("+".join(buttons) if buttons else "none", lx, ly, rx, ry)


def load_events(path: Path, max_seconds: float) -> list[tuple[float, bool, str]]:
    document = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(document, list):
        raise ValueError("input sequence must be a JSON array")
    edges: list[tuple[float, bool, str]] = []
    for index, item in enumerate(document):
        if not isinstance(item, dict) or set(item) - {"at", "key", "hold"}:
            raise ValueError(f"event {index}: expected at/key/hold fields")
        at = item.get("at")
        hold = item.get("hold", 0.35)
        key = item.get("key")
        if (
            type(at) not in (int, float)
            or type(hold) not in (int, float)
            or not math.isfinite(at)
            or not math.isfinite(hold)
            or at < 0
            or hold <= 0
            or at + hold > max_seconds
            or key not in VALID_KEYS
        ):
            raise ValueError(f"event {index}: invalid event")
        edges.append((float(at), True, key))
        edges.append((float(at + hold), False, key))
    # Releases at a timestamp must apply before presses at the same timestamp.
    return sorted(edges, key=lambda edge: (edge[0], 1 if edge[1] else 0, edge[2]))


def convert(input_path: Path, output_path: Path, max_seconds: float, label: str) -> None:
    edges = load_events(input_path, max_seconds)
    active: set[str] = set()
    rows: list[str] = [
        "# Generated by scripts/convert_input_sequence_to_pad.py",
        f"# Source: {input_path.as_posix()}",
        f"# Label: {label}",
        "# Format: at seconds buttons lx ly rx ry",
        "at 0 none",
    ]

    index = 0
    while index < len(edges):
        timestamp = edges[index][0]
        while index < len(edges) and edges[index][0] == timestamp:
            _, down, key = edges[index]
            if down:
                active.add(key)
            else:
                active.discard(key)
            index += 1
        buttons, lx, ly, rx, ry = active_frame(active)
        rows.append(f"at {fmt_time(timestamp)} {buttons} {lx} {ly} {rx} {ry}")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(rows) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--seconds", type=float, required=True)
    parser.add_argument("--label", required=True)
    args = parser.parse_args()
    convert(args.input, args.output, args.seconds, args.label)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
